dataset:
    name:   'shd'
    path_to_dataset:    '/home/sl220/Documents/data/SHD-SSC/SHD/'
    num_classes:    20
    input_size: 700
learning:
    batch_size:     128
    lr:   1e-3
    lr_decay:   False
    weight_decay:   0.0001
    epochs:  80
    clip_norm: 10
network:
    neuron_type: 'culif'
    hidden_size: 256
simulation:
    dt: 10      #dt, Ts, sampling time in ms
    T:   80     #nSample, chunk_size, num of bins
    T_empty: 20    # add empty sequence
neuron_params1:
    tau_m:    5.
    tau_s:    5.
    theta:    5.0
neuron_params2:
    tau_m:    60
    tau_s:    60
    theta:    10.0
loss:
    loss_mode:   'first_time' #'first_time' ' #'firing_rate'
    FS:
        alpha: 0.2
        D: 16 # sigma=T/D, determine the window size
        A: 200 # Amplitude of Gaussian kernel
    FR:
        alpha: 20
    # Constraints for dead neurons (large FS timing)
    treg:
        lambda: 0.01
        beta: 0.02