dataset:
    name:   'dvsplane'
    path_to_dataset:    '/home/sl220/Documents/data/DVSPlane/'
    num_classes:    4
    input_size: [2,60,76]
learning:
    batch_size:     16
    lr:   3e-4
    lr_decay:   False
    weight_decay:   0.0001
    epochs:  40
    clip_norm: 10
network:
    neuron_type: 'culif'
    hidden_size: 128
simulation:
    dt: 2      #dt, Ts, sampling time in ms
    T:   135     #nSample, chunk_size, num of bins
    T_empty: 0    # add empty sequence
neuron_params1:
    tau_m:    5
    tau_s:    5
    theta:    0.5
neuron_params2:
    tau_m:    40
    tau_s:    40
    theta:    2.0 #0.5
loss:
    loss_mode:   'first_time' #'first_time' ' #'firing_rate'
    FS:
        alpha: 0.1
        D: 8 # sigma=T/D, determine the window size
        A: 500 # Amplitude of Gaussian kernel
    FR:
        alpha: 15
    # Constraints for dead neurons (large FS timing)
    treg:
        lambda: 0.01
        beta: 0.02